### ISSUE TITLE
Links in copy inconsistent target

### ISSUE THREAD

**Issue by varffs** [interglobalvision/bienal-de-fotografia#27]
Some open _blank others don't. All should.

**Comment by mixcas** [comment]
where?

**Comment by varffs** [comment]
Link to the rules in the application intro

**Comment by mixcas** [comment]
can u plz link me to something? 
I see all links to the rules with _blank

**Comment by varffs** [comment]
It happens for me on this link: https://github.com/interglobalvision/bienal-de-fotografia/blob/master/app/i18n/es.i18n.json#L104

But clearly that has target so idgi

**Comment by mixcas** [comment]
uhhh weird

**Comment by mixcas** [comment]
closed in 17e2b76

**Comment by varffs** [comment]
ah typos. Surely there should be some automated way to check the validity of html props? Anyhow
