### ISSUE TITLE
No Juice Error fix

### ISSUE THREAD

**Issue by mixcas** [interglobalvision/bienal-de-fotografia#60]
fuck that `Error: You must be more powerful aka No Juice Error` we r getting thos in kadira, im guessing from the role checks implemented in the publications, but with such generic error its hard to trance whats failing.

**Comment by varffs** [comment]
Errors are generic as returned to the client. Especially bad permissions errors

**Comment by mixcas** [comment]
so we should not improve this? how r we supposed to fix the bunch of errors in kadira related this?

**Comment by varffs** [comment]
http://docs.meteor.com/#/full/meteor_error We could add the 3rd param with a code that only means something to us. Like `Error: 3456` and then just make sure we save somewhere what those errors mean for debugging

**Comment by mixcas** [comment]
fixed in fa3145cce6b3e3338c821df47b5927251b64bc15
